### PR TITLE
show logos below title

### LINKED ISSUE #174: add logos on top of page title
- image is in ``img/logos.png``
- currently at bottom of info tab, but it would be nice to present the logos more prominently
grafik

### PR DESCRIPTION
**Pull request by joAschauer**
I put the logo inside a st.column in order to reduce the width dynamically.

resolves #174

### CODE REVIEW

**Review by markushal — CHANGES_REQUESTED** [review]
to be honest, that looks horrible :). I would either have it above the title or at the bottom of the page, but not between title and tab navigation

**Comment by markushal** [comment]
Good morning! This still looks too intrusive, I think. I would prefer to have the logos at the bottom of each page, after all. How about putting the last container of the info tab below each page as a footer, complete with authorship information?

grafik

**Comment by joAschauer** [comment]
> Good morning! This still looks too intrusive, I think. I would prefer to have the logos at the bottom of each page, after all. How about putting the last container of the info tab below each page as a footer, complete with authorship information?


Yes, lets do this.

**Comment by joAschauer** [comment]
@markushal I think this is better, please have a look.

**Review by markushal — APPROVED** [review]
**much** better, thanks!

**Pull request merged**
