### PR TITLE
18 implement input data editing

### PR DESCRIPTION
**Pull request by markushal**
@joAschauer editing data and resetting it now works within this branch. I also tried to merge develop into this branch, but this breaks the app like you showed me & makes testing its functionality difficult. This is why I reverted the merge process. Should we merge this branch into develop now?

### CODE REVIEW

**Comment by joAschauer** [comment]
I think the thousands separator (,) in the input data makes it quite confusing to edit data. See the screenshot below. I included 3000 for Australia:
grafik

Maybe a fixed column format would help? Suggenstion: Always show 3 digits after comma, remove thousands separator.

**Comment by joAschauer** [comment]
@markushal the editing in the frontend looks ready to merge. Should we also make use of the input data in the backend in this PR or split it up into another PR?

**Review by joAschauer — APPROVED** [review]

**Comment by markushal** [comment]
> I think the thousands separator (,) in the input data makes it quite confusing to edit data. See the screenshot below. I included 3000 for Australia: grafik
> 
> Maybe a fixed column format would help? Suggenstion: Always show 3 digits after comma, remove thousands separator.

yes, that is a good idea. I will fix this #70

**Comment by markushal** [comment]
> Is it intential that the modified Input Data is lost when the user unsets the "Edit input data" switch in the sidebar and then turns it on again?

Yes, this is intentional. I will create an issue to improve on this #71

**Comment by markushal** [comment]
> @markushal the editing in the frontend looks ready to merge. Should we also make use of the input data in the backend in this PR or split it up into another PR?

lets do this in a separate PR.

**Pull request merged**
