### PR TITLE
update data with Agora LOHC Database

### PR DESCRIPTION
**Pull request by joAschauer**

### CODE REVIEW

**Comment by joAschauer** [comment]
@wingechr @markushal this is now ready, I updated the test results.

**Review by markushal — COMMENTED** [review]
Why does git consider all lines as changed? Data has only changed for a small number of lines

grafik


In VSC only lines with updated data are considered as changed. Is this a line ending issue?

grafik

Also, I noticed that not only CAPEX has been changed, but losses as well (see screenshot for an example). Is this intentional?

**Comment by joAschauer** [comment]
> Why does git consider all lines as changed? Data has only changed for a small number of lines

It was a line ending issue, I pushed the files again with LF endings, now you can see the diffs properly https://github.com/agoenergy/ptx-boa/pull/244/commits/5cbd73f5b4cd853bf75d097595612299ce20515c

**Comment by markushal** [comment]
> > Why does git consider all lines as changed? Data has only changed for a small number of lines
> 
> It was a line ending issue, I pushed the files again with LF endings, now you can see the diffs properly [5cbd73f](https://github.com/agoenergy/ptx-boa/commit/5cbd73f5b4cd853bf75d097595612299ce20515c)

Great. I would still like to know if the changes in the ``LOSSES`` parameter are intentional.

**Comment by joAschauer** [comment]
> Great. I would still like to know if the changes in the `LOSSES` parameter are intentional.

I checked with Roman and Christoph, its intentional

**Review by markushal — APPROVED** [review]

**Pull request merged**
