### PR TITLE
improve help texts and input data representation

### LINKED ISSUE #182: show specific costs on input data tab

### LINKED ISSUE #183: configure columns for dataframe in a single place

### PR DESCRIPTION
**Pull request by markushal**
- closes #182 
- closes #183

### CODE REVIEW

**Comment by markushal** [comment]
@joAschauer could you have a look at this?

commit https://github.com/agoenergy/ptx-boa/pull/184/commits/02fee082f1ef11869ef15869c4338f76f9dfe3da adds a bug: Displaying specific costs works fine, but when I try to edit them, this raises an exception: 
grafik

I think there is a problem with this code in ``_update_scenario_data_with_user_data``
````py
        # user data from frontend only has columns
        # "source_region_code", "process_code", "value" and "parameter_code", we need
        # replace missing columns "flow_code" and "target_country_code"
        for missing_dim in ["flow_code", "target_country_code"]:
            user_data[missing_dim] = ""
````

**Comment by joAschauer** [comment]
> commit [02fee08](https://github.com/agoenergy/ptx-boa/commit/02fee082f1ef11869ef15869c4338f76f9dfe3da) adds a bug: Displaying specific costs works fine, but when I try to edit them, this raises an exception:

@markushal this is because the user modification data does not conform anymore with the format required from the api. 
grafik

The required format is documented here:
https://github.com/agoenergy/ptx-boa/blob/b66175378fd2533ffe463a7c54de99243b883afb/ptxboa/api.py#L96-L100

Do we need to add `flow_code` as a column to `user_data`?

**Comment by markushal** [comment]
> > commit [02fee08](https://github.com/agoenergy/ptx-boa/commit/02fee082f1ef11869ef15869c4338f76f9dfe3da) adds a bug: Displaying specific costs works fine, but when I try to edit them, this raises an exception:
> 
> @markushal this is because the user modification data does not conform anymore with the format required from the api. grafik
> 
> The required format is documented here:
> 
> https://github.com/agoenergy/ptx-boa/blob/b66175378fd2533ffe463a7c54de99243b883afb/ptxboa/api.py#L96-L100
> 
> Do we need to add `flow_code` as a column to `user_data`?

Unfortunately yes, i think so. only for specific costs, but these are important data points that we need to make editable

**Review by joAschauer — APPROVED** [review]
👍

**Pull request merged**
