### PR TITLE
deep dive country maps

### PR DESCRIPTION
**Pull request by joAschauer**
Hi Markus,
I changed the plot function for costs on a map and added maps for the deep dive countries, please have a look. 

I also added the changed colorbar height and figure size from #117

### CODE REVIEW

**Comment by joAschauer** [comment]
closes #116

**Comment by markushal** [comment]
Somethin is wrong with the morocco subregions. They cover only a small section of the country, and names and shapes are not assigned correctly (eg Casablanca should be on the west coast)

grafik

**Comment by markushal** [comment]
Can we adjust the xy range for the south africa map to only include the mainland? It is zoomed out very far because of two small islands far to the south

grafik

**Comment by markushal** [comment]
the south africa map also seems to have some subregions missing: 

country map: 
grafik


subregions map: 
grafik

**Review by markushal — COMMENTED** [review]
I like the way you implemented this! If the bugs I mentioned in the conversation are fixed (errors on the data side, most likely) this can be merged. 

We also need to display flh on maps, will we deal with this in a separate PR?

**Comment by joAschauer** [comment]
Hi @markushal, thanks for checking and catching errors. I addressed your points, should work as expected now.

**Review by markushal — APPROVED** [review]

**Pull request merged**
